config/routes.rb
Rails.application.routes.draw do

  resources :cards
resources :contacts, only: [:new, :create]
  resources :accounts do
    resources :transfers
    resources :deposits
  end
  resources :transfers do
    resources :otps
  end
  resources :transactions, only: [:index]
  devise_for :users
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  resources :pages, only: [:show]
  authenticated :user do
    root 'accounts#index', as: "authenticated_root"
  end
    root "welcome#index"
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/account.rb
class Account < ApplicationRecord
  mount_uploader :image, ImageUploader
  extend FriendlyId
  friendly_id :account_number, use: :slugged
  belongs_to :user
  has_many :transfers, dependent: :destroy
  has_many :deposits, dependent: :destroy
  accepts_nested_attributes_for :transfers

  validates :user, presence: true
  validates :account_balance, presence: true
  before_validation :load_defaults

  def load_defaults
    if self.new_record?
      self.account_balance = 0.00
      length = 8
      self.account_number = SecureRandom.random_number(10000000000)
      self.routine_number = SecureRandom.random_number(100000000)
      self.confirmed = "false"
    end
  end

end

app/models/admin_user.rb
class AdminUser < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, 
         :recoverable, :rememberable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/card.rb
class Card < ApplicationRecord
  belongs_to :user
  before_validation :load_defaults

  def load_defaults
    if self.new_record?
      length = 8
      self.card_number = SecureRandom.random_number(10000000000000000)
      self.cvv = SecureRandom.random_number(1000)
      self.status = "false"
    end
  end
end

app/models/contact.rb
class Contact < MailForm::Base
    attribute :name,      :validate => true
    attribute :email,     :validate => /\A([\w\.%\+\-]+)@([\w\-]+\.)+([\w]{2,})\z/i
    attribute :file,      :attachment => true
    attribute :message
    attribute :nickname,  :captcha  => true

  # Declare the e-mail headers. It accepts anything the mail method
  # in ActionMailer accepts.

  def headers
      {
        :subject => "Support Request ",
        :to => "support@reylgroup.com",
        :from => %("#{name}" <#{email}>)
      }
    end
end

app/models/deposit.rb
class Deposit < ApplicationRecord
  belongs_to :account
  belongs_to :user
end

app/models/news.rb
class News < ApplicationRecord
end

app/models/otp.rb
class Otp < ApplicationRecord
  belongs_to :account
  belongs_to :transfer
  belongs_to :user
end

app/models/transfer.rb
class Transfer < ApplicationRecord
  belongs_to :user
  belongs_to :account
  has_many :otps
  accepts_nested_attributes_for :otps

  before_validation :load_defaults

  def load_defaults
    if self.new_record?
      self.otp = SecureRandom.random_number(1000000)
      self.status = "In Progress"
    end
  end
end

app/models/user.rb
class User < ApplicationRecord
  mount_uploader :avatar, AvatarUploader

  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable, :confirmable, :lockable
has_many :accounts
has_many :transfers
has_many :otps
has_many :deposits
has_many :cards
end

app/helpers/accounts_helper.rb
module AccountsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/cards_helper.rb
module CardsHelper
end

app/helpers/contacts_helper.rb
module ContactsHelper
end

app/helpers/deposits_helper.rb
module DepositsHelper
end

app/helpers/news_helper.rb
module NewsHelper
end

app/helpers/otps_helper.rb
module OtpsHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/transfers_helper.rb
module TransfersHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/layouts/accounts.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Online Account </title>
    <%= csrf_meta_tags %>
    <meta name="format-detection" content="telephone=no"/>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta content="width=device-width, initial-scale=1.0" name="viewport" />
    <meta name="description"  content=" Have all your banking information right at your hands using our online platform we provide all services best for you"/>

    <%= stylesheet_link_tag    'accounts', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'accounts', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <div class="wrapper">
      <% if Account.where(user_id: current_user.id).exists?%>

      <%= render "shared/sidebar" %>
      <%= render "shared/headermenu" %>
      <% else %>
      <%end %>

      <% if notice %>
    <div class="col-md-8 col-md-offset-2">
    <div class="alert alert-info alert-with-icon" data-notify="container">
                                  <button type="button" aria-hidden="true" class="close">×</button>
                                  <span data-notify="icon" class="ti-bell"></span>
                                  <span data-notify="message"><%= notice %>.</span>
                              </div>
                            </div>
                              <% end %>
    <%= yield %>
  </div>
  </body>
</html>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>REYL & CIE GROUP </title>
    <%= csrf_meta_tags %>
    <meta name="format-detection" content="telephone=no"/>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta content="width=device-width, initial-scale=1.0" name="viewport" />
    <meta name="description"  content=" Have all your banking information right at your hands using our online platform we provide all services best for you"/>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <div class="page">
      <% if notice %>
      <div class="col-md-8 col-md-offset-2">
      <div class="alert alert-info alert-with-icon" data-notify="container">
                                    <button type="button" aria-hidden="true" class="close">×</button>
                                    <span data-notify="icon" class="ti-bell"></span>
                                    <span data-notify="message"><%= notice %>.</span>
                                </div>
                              </div>
                    <% end %>
                  <% if alert %>
                        <div class="col-md-8 col-md-offset-2">
                          <div class="alert alert-info alert-with-icon" data-notify="container">
                            <button type="button" aria-hidden="true" class="close">×</button>
                            <span data-notify="icon" class="ti-bell"></span>
                            <span data-notify="message"><%= alert %>.</span>
                                </div>
                                  </div>
                                    <% end %>
      <%= render "shared/header" %>
    <%= yield %>
    <%= render "shared/footer" %>
  </div>
  </body>
</html>

app/views/layouts/devise.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Online Access </title>
    <%= csrf_meta_tags %>
    <meta name="format-detection" content="telephone=no"/>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta content="width=device-width, initial-scale=1.0" name="viewport" />
    <meta name="description"  content=" Have all your banking information right at your hands using our online platform we provide all services best for you"/>

    <%= stylesheet_link_tag    'accounts', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'accounts', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <% if notice %>
    <div class="col-md-8 col-md-offset-2">
    <div class="alert alert-info alert-with-icon" data-notify="container">
                                  <button type="button" aria-hidden="true" class="close">×</button>
                                  <span data-notify="icon" class="ti-bell"></span>
                                  <span data-notify="message"><%= notice %>.</span>
                              </div>
                            </div>
                              <% end %>
                              <% if alert %>
                              <div class="col-md-8 col-md-offset-2">
                              <div class="alert alert-info alert-with-icon" data-notify="container">
                                                            <button type="button" aria-hidden="true" class="close">×</button>
                                                            <span data-notify="icon" class="ti-bell"></span>
                                                            <span data-notify="message"><%= alert %>.</span>
                                                        </div>
                                                      </div>
                                                        <% end %>
    <div class="wrapper">
      <div class="content">
          <div class="container-fluid">
            <div class="col-md-8 col-md-offset-2">
              <div class="content text-center" style="padding:20px;">
                <%= image_tag "logo.svg", class: "img-responive" %>
              </div>
            </div>
          </div>
        </div>

    <%= yield %>
  </div>
  </body>
</html>

app/views/shared/_footer.html.erb
<footer>
    <section class="well-xs well-xs--inset-1">
        <div class="container">
            <div class="row flow-offset-1">
                <div class="col-xs-12 col-sm-12 col-md-6 col-lg-3">
                    <h6 class="ubold">About</h6>
                    <ul class="list">
                        <li><%= link_to page_path("about") do %>
                            HISTORY
                        <% end %></li>
                        <li><%= link_to page_path("about") do %>
                            REYL GROUP
                        <% end %></li>
                        <li><%= link_to page_path("about") do %>
                            OBJECTIVES
                        <% end %></li>

                    </ul>
                </div>
                <div class="col-xs-12 col-sm-12 col-md-6 col-lg-3">
                    <h6 class="ubold">Services </h6>
                    <ul class="list">
                      <li><%= link_to page_path("service") do %>
                          WEALTH MANAGEMENT
                      <% end %></li>
                      <li><%= link_to page_path("service") do %>
                          CORPORATE & FAMILY GOVERNANCE
                      <% end %></li>
                      <li><%= link_to page_path("service") do %>
                          CORPORATE ADVISORY & STRUCTURING
                      <% end %></li>
                      <li><%= link_to page_path("service") do %>
                          ASSET SERVICES
                      <% end %></li>
                      <li><%= link_to page_path("service") do %>
                          ASSET MANAGEMENT
                      <% end %></li>

                    </ul>
                </div>
                <div class="col-xs-12 col-sm-12 col-md-6 col-lg-3">

                    <h6 class="ubold">Contact</h6>
                    <address>
                        <dl>
                            <dt>Need help?</dt>

                        <dl>
                            <dt> E-mail:</dt>
                            <dd>
                                <a href="mailto:support@reylgroup.comm">
                                    support@reylgroup.com</a>
                            </dd>

                        </dl>
                    </address>

                </div>
                <div class="col-xs-12 col-sm-12 col-md-6 col-lg-3">
                    <%= image_tag "footer.svg", class: "img-reponsive" %>
                </div>
            </div>
        </div>
    </section>


</footer>

app/views/shared/_header.html.erb
<!--========================================================
                          HEADER
=========================================================-->
<header>
    <div id="stuck_container" class="stuck_container">
        <div class="container">

            <div class="brand">

                <div class="brand_name">
                  <%= link_to  "R&C", root_path %>
                </div>

                <p class="brand_slogan inset-2">
                    Group
                </p>
            </div>

            <nav class="nav">
                <ul class="sf-menu" data-type="navbar">
                    <li class="active">
                      <%= link_to  "Home", root_path %>
                    </li>
                    <li>  <%= link_to "About", page_path("about") %>
                    </li>
                    <li>   <%= link_to "Services", page_path("service") %>
                    </li>

                    <li>
                        <%= link_to "Contact Us", new_contact_path %>
                    </li>
                    <li>
                        <%= link_to "Get Started", new_user_registration_path %>
                    </li>
                    <li><%= link_to "Login", new_user_session_path, class: "btn btn-primary btn-md" %>
                </ul>
            </nav>
        </div>
    </div>

</header>
<!--========================================================
                          CONTENT
=========================================================-->

app/views/shared/_headermenu.html.erb
<div class="main-panel">
  <nav class="navbar navbar-default">
    <div class="container-fluid">
      <div class="navbar-header">
        <button type="button" class="navbar-toggle">
          <span class="sr-only">Toggle navigation</span>
          <span class="icon-bar bar1"></span>
          <span class="icon-bar bar2"></span>
          <span class="icon-bar bar3"></span>
        </button>
        <a class="navbar-brand" href="#">Dashboard</a>
      </div>
      <div class="collapse navbar-collapse">
        <ul class="nav navbar-nav navbar-right">
          <li>
            <a href="#" class="dropdown-toggle" data-toggle="dropdown">
              <i class="ti-panel"></i>
              <p><%= current_user.email %></p>
            </a>
          </li>

          <li>
            <%= link_to destroy_user_session_path, method: :delete do %>

              <i class="ti-arrow-left"></i>
              <p>log out</p>
            <% end %>
          </li>
        </ul>

      </div>
    </div>
  </nav>

app/views/shared/_sidebar.html.erb
<div class="sidebar" >


<!--
Tip 1: you can change the color of the sidebar's background using: data-background-color="white | black"
Tip 2: you can change the color of the active button using the data-active-color="primary | info | success | warning | danger"
-->

  <div class="sidebar-wrapper">
        <div class="logo">
            <%= current_user.email %>
        </div>

        <ul class="nav">
            <li class="active">
                <%= link_to accounts_path do %>
                    <i class="ti-panel"></i>
                    <p>Account</p>
                <% end %>
            </li>
            <li>
              <%= link_to edit_user_registration_path do %>
                    <i class="ti-user"></i>
                    <p>User Profile</p>
                <% end %>
            </li>
            <li>
                <%= link_to transactions_path do %>
                    <i class="ti-pulse"></i>
                    <p>Transaction  History </p>
                  <%end%>
            </li>
            <li>
              <%= link_to cards_path do %>
                    <i class="ti-credit-card"></i>
                    <p>Manage Cards</p>
                    <%end%>
            </li>


            <li>
              <%= link_to destroy_user_session_path, method: :delete do %>

                    <i class="ti-arrow-left"></i>
                    <p>Sign-out</p>
                </a>
            <% end %>

        </ul>
  </div>
</div>

app/views/shared/_slider.html.erb
<main>
  <!--Start Slider-->

  <div id="owl-carousel" class=" owl-carousel owl-theme slider">

    <div class="item  text-center" style="background-image: url(<%= asset_path 'page-1_slide1.jpg' %>); ">

      <div class="container" >
        <div class="col-md-8 col-md-offset-2 pt-1">
          <h1 >
            <span class="ubold">Go from financial stress</span> <br>

to financial yes.
          </h1>

          <div class="row">

            <div class="text-center">
              <%= link_to new_user_session_path, class: "btn btn-primary btn-md" do %>
                Start Now
              <% end %>>
            </div>

          </div>

        </div>
      </div>
    </div>
    <div class="item  text-center" style="background-image: url(<%= asset_path 'page-1_slide2.jpg' %>); ">
      <div class="container">
        <div class="col-md-8 col-md-offset-2 pt-1 ">

          <h1>
            <span class="ubold">Get reliable help with your credit card <br>
              processing needs</span>
            </h1>

            <div class="row">

              <div class="text-center">
                <%= link_to new_user_session_path, class: "btn btn-primary btn-md" do %>
                  Start Now
                <% end %>>
              </div>

            </div>
          </div>
        </div>
      </div>
    <div class="item  text-center" style="background-image: url(<%= asset_path 'page-1_slide3.jpg' %>); ">

        <div class="container" >
          <div class="col-md-8 col-md-offset-2 pt-1">
            <h1 >
              <span class="ubold">Products and services<br>
                to make banking easy</span>
              </h1>

              <div class="row">

                <div class="text-center">
                  <%= link_to new_user_session_path, class: "btn btn-primary btn-md" do %>
                    Start Now
                  <% end %>>
                </div>

              </div>
            </div>
          </div>
        </div>

  </div>


      <!--End Slider-->