config/routes.rb
Rails.application.routes.draw do

  resources :cards
resources :contacts, only: [:new, :create]
  resources :accounts do
    resources :transfers
    resources :deposits
  end
  resources :transfers do
    resources :otps
  end
  resources :transactions, only: [:index]
  devise_for :users
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  resources :pages, only: [:show]
  authenticated :user do
    root 'accounts#index', as: "authenticated_root"
  end
    root "welcome#index"
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/account.rb
class Account < ApplicationRecord
  mount_uploader :image, ImageUploader
  extend FriendlyId
  friendly_id :account_number, use: :slugged
  belongs_to :user
  has_many :transfers, dependent: :destroy
  has_many :deposits, dependent: :destroy
  accepts_nested_attributes_for :transfers

  validates :user, presence: true
  validates :account_balance, presence: true
  before_validation :load_defaults

  def load_defaults
    if self.new_record?
      self.account_balance = 0.00
      length = 8
      self.account_number = SecureRandom.random_number(10000000000)
      self.routine_number = SecureRandom.random_number(100000000)
      self.confirmed = "false"
    end
  end

end

app/models/admin_user.rb
class AdminUser < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, 
         :recoverable, :rememberable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/card.rb
class Card < ApplicationRecord
  belongs_to :user
  before_validation :load_defaults

  def load_defaults
    if self.new_record?
      length = 8
      self.card_number = SecureRandom.random_number(10000000000000000)
      self.cvv = SecureRandom.random_number(1000)
      self.status = "false"
    end
  end
end

app/models/contact.rb
class Contact < MailForm::Base
    attribute :name,      :validate => true
    attribute :email,     :validate => /\A([\w\.%\+\-]+)@([\w\-]+\.)+([\w]{2,})\z/i
    attribute :file,      :attachment => true
    attribute :message
    attribute :nickname,  :captcha  => true

  # Declare the e-mail headers. It accepts anything the mail method
  # in ActionMailer accepts.

  def headers
      {
        :subject => "Support Request ",
        :to => "support@reylgroup.com",
        :from => %("#{name}" <#{email}>)
      }
    end
end

app/models/deposit.rb
class Deposit < ApplicationRecord
  belongs_to :account
  belongs_to :user
end

app/models/news.rb
class News < ApplicationRecord
end

app/models/otp.rb
class Otp < ApplicationRecord
  belongs_to :account
  belongs_to :transfer
  belongs_to :user
end

app/models/transfer.rb
class Transfer < ApplicationRecord
  belongs_to :user
  belongs_to :account
  has_many :otps
  accepts_nested_attributes_for :otps

  before_validation :load_defaults

  def load_defaults
    if self.new_record?
      self.otp = SecureRandom.random_number(1000000)
      self.status = "In Progress"
    end
  end
end

app/models/user.rb
class User < ApplicationRecord
  mount_uploader :avatar, AvatarUploader

  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable, :confirmable, :lockable
has_many :accounts
has_many :transfers
has_many :otps
has_many :deposits
has_many :cards
end

app/controllers/deposits_controller.rb
class DepositsController < InheritedResources::Base

  private

    def deposit_params
      params.require(:deposit).permit(:type, :amount, :status, :depositors_name, :date, :account_id, :user_id)
    end
end

app/controllers/news_controller.rb
class NewsController < InheritedResources::Base

  private

    def news_params
      params.require(:news).permit(:title, :body, :date)
    end
end

app/controllers/otps_controller.rb
class OtpsController < ApplicationController
  layout "account"
    #before_action :find_Account
    before_action :authenticate_user!

def new


end
    def create
      @transfer = Transfer.find(params[:transfer_id])
      @otp = @transfer.otps.create(otp_params)
      @otp.user_id = current_user.id

         redirect_to root_path, notice: "transfer successfully confirmed and in progress"

    end

    private
    def find_account
      @account = Account.find(params[:id])
    end
    def find_transfer
      @transfer = @account.transfers.find(params[:id])
    end

    def find_otp
    end

    def otp_params
      params.require(:otp).permit( :transfer_id, :user_id, :account_id, :otp)
    end

end

app/helpers/accounts_helper.rb
module AccountsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/cards_helper.rb
module CardsHelper
end

app/helpers/contacts_helper.rb
module ContactsHelper
end

app/helpers/deposits_helper.rb
module DepositsHelper
end

app/helpers/news_helper.rb
module NewsHelper
end

app/helpers/otps_helper.rb
module OtpsHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/transfers_helper.rb
module TransfersHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/deposits/_deposit.html.erb
<tr>

                         <td><%= deposit.payment_method %></td>
                         <td><%= deposit.depositors_name %></td>
                         <td>$<%= deposit.amount%></td>
                         <td><%= deposit.status %></td>
</tr>

app/views/deposits/_form.html.erb
<%= simple_form_for(@deposit) do |f| %>
  <%= f.error_notification %>
  <%= f.error_notification message: f.object.errors[:base].to_sentence if f.object.errors[:base].present? %>

  <div class="form-inputs">
    <%= f.input :type %>
    <%= f.input :amount %>
    <%= f.input :status %>
    <%= f.input :depositors_name %>
    <%= f.input :date %>
    <%= f.input :account_id %>
    <%= f.association :user %>
  </div>

  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/deposits/edit.html.erb
<h1>Editing Deposit</h1>

<%= render 'form', deposit: @deposit %>

<%= link_to 'Show', @deposit %> |
<%= link_to 'Back', deposits_path %>

app/views/deposits/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Deposits</h1>

<table>
  <thead>
    <tr>
      <th>Type</th>
      <th>Amount</th>
      <th>Status</th>
      <th>Depositors name</th>
      <th>Date</th>
      <th>Account</th>
      <th>User</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @deposits.each do |deposit| %>
      <tr>
        <td><%= deposit.type %></td>
        <td><%= deposit.amount %></td>
        <td><%= deposit.status %></td>
        <td><%= deposit.depositors_name %></td>
        <td><%= deposit.date %></td>
        <td><%= deposit.account_id %></td>
        <td><%= deposit.user %></td>
        <td><%= link_to 'Show', deposit %></td>
        <td><%= link_to 'Edit', edit_deposit_path(deposit) %></td>
        <td><%= link_to 'Destroy', deposit, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Deposit', new_deposit_path %>

app/views/deposits/new.html.erb
<h1>New Deposit</h1>

<%= render 'form', deposit: @deposit %>

<%= link_to 'Back', deposits_path %>

app/views/deposits/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Type:</strong>
  <%= @deposit.type %>
</p>

<p>
  <strong>Amount:</strong>
  <%= @deposit.amount %>
</p>

<p>
  <strong>Status:</strong>
  <%= @deposit.status %>
</p>

<p>
  <strong>Depositors name:</strong>
  <%= @deposit.depositors_name %>
</p>

<p>
  <strong>Date:</strong>
  <%= @deposit.date %>
</p>

<p>
  <strong>Account:</strong>
  <%= @deposit.account_id %>
</p>

<p>
  <strong>User:</strong>
  <%= @deposit.user %>
</p>

<%= link_to 'Edit', edit_deposit_path(@deposit) %> |
<%= link_to 'Back', deposits_path %>