config/routes.rb
Rails.application.routes.draw do

  resources :cards
resources :contacts, only: [:new, :create]
  resources :accounts do
    resources :transfers
    resources :deposits
  end
  resources :transfers do
    resources :otps
  end
  resources :transactions, only: [:index]
  devise_for :users
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  resources :pages, only: [:show]
  authenticated :user do
    root 'accounts#index', as: "authenticated_root"
  end
    root "welcome#index"
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/account.rb
class Account < ApplicationRecord
  mount_uploader :image, ImageUploader
  extend FriendlyId
  friendly_id :account_number, use: :slugged
  belongs_to :user
  has_many :transfers, dependent: :destroy
  has_many :deposits, dependent: :destroy
  accepts_nested_attributes_for :transfers

  validates :user, presence: true
  validates :account_balance, presence: true
  before_validation :load_defaults

  def load_defaults
    if self.new_record?
      self.account_balance = 0.00
      length = 8
      self.account_number = SecureRandom.random_number(10000000000)
      self.routine_number = SecureRandom.random_number(100000000)
      self.confirmed = "false"
    end
  end

end

app/models/admin_user.rb
class AdminUser < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, 
         :recoverable, :rememberable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/card.rb
class Card < ApplicationRecord
  belongs_to :user
  before_validation :load_defaults

  def load_defaults
    if self.new_record?
      length = 8
      self.card_number = SecureRandom.random_number(10000000000000000)
      self.cvv = SecureRandom.random_number(1000)
      self.status = "false"
    end
  end
end

app/models/contact.rb
class Contact < MailForm::Base
    attribute :name,      :validate => true
    attribute :email,     :validate => /\A([\w\.%\+\-]+)@([\w\-]+\.)+([\w]{2,})\z/i
    attribute :file,      :attachment => true
    attribute :message
    attribute :nickname,  :captcha  => true

  # Declare the e-mail headers. It accepts anything the mail method
  # in ActionMailer accepts.

  def headers
      {
        :subject => "Support Request ",
        :to => "support@reylgroup.com",
        :from => %("#{name}" <#{email}>)
      }
    end
end

app/models/deposit.rb
class Deposit < ApplicationRecord
  belongs_to :account
  belongs_to :user
end

app/models/news.rb
class News < ApplicationRecord
end

app/models/otp.rb
class Otp < ApplicationRecord
  belongs_to :account
  belongs_to :transfer
  belongs_to :user
end

app/models/transfer.rb
class Transfer < ApplicationRecord
  belongs_to :user
  belongs_to :account
  has_many :otps
  accepts_nested_attributes_for :otps

  before_validation :load_defaults

  def load_defaults
    if self.new_record?
      self.otp = SecureRandom.random_number(1000000)
      self.status = "In Progress"
    end
  end
end

app/models/user.rb
class User < ApplicationRecord
  mount_uploader :avatar, AvatarUploader

  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable, :confirmable, :lockable
has_many :accounts
has_many :transfers
has_many :otps
has_many :deposits
has_many :cards
end

app/controllers/cards_controller.rb
class CardsController < InheritedResources::Base
layout "accounts"
  before_action :find_card, only: [ :show, :edit, :update, :destroy]
  before_action :authenticate_user!

  def index
    @users = User.where(user_id: current_user)
    @accounts = Account.where(user_id: current_user).order('created_at DESC')
    @cards = Card.where(user_id: current_user).order('created_at DESC')
  end

  def show
  end

  def new
    @card = current_user.cards.build
  end
  def create
    @card = current_user.cards.build(card_params)
    if @card.save
      user = User.find_by_id(@card.user_id)
      card = @card
      CardMailer.card_email(user, card).deliver
      redirect_to cards_path, notice: "Card Request Made And In Progress"
    else
    render 'new'
  end
  end

  private
   def find_card
     @card = Card.find(params[:id])
   end
    def card_params
      params.require(:card).permit(:card_type, :pin, :veriy_pin, :card_number, :cvv, :expiry, :card_name, :account_id, :user_id)
    end
end

app/controllers/news_controller.rb
class NewsController < InheritedResources::Base

  private

    def news_params
      params.require(:news).permit(:title, :body, :date)
    end
end

app/controllers/otps_controller.rb
class OtpsController < ApplicationController
  layout "account"
    #before_action :find_Account
    before_action :authenticate_user!

def new


end
    def create
      @transfer = Transfer.find(params[:transfer_id])
      @otp = @transfer.otps.create(otp_params)
      @otp.user_id = current_user.id

         redirect_to root_path, notice: "transfer successfully confirmed and in progress"

    end

    private
    def find_account
      @account = Account.find(params[:id])
    end
    def find_transfer
      @transfer = @account.transfers.find(params[:id])
    end

    def find_otp
    end

    def otp_params
      params.require(:otp).permit( :transfer_id, :user_id, :account_id, :otp)
    end

end

app/helpers/accounts_helper.rb
module AccountsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/cards_helper.rb
module CardsHelper
end

app/helpers/contacts_helper.rb
module ContactsHelper
end

app/helpers/deposits_helper.rb
module DepositsHelper
end

app/helpers/news_helper.rb
module NewsHelper
end

app/helpers/otps_helper.rb
module OtpsHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/transfers_helper.rb
module TransfersHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/cards/_form.html.erb
<%= simple_form_for(@card) do |f| %>
  <%= f.error_notification %>
  <%= f.error_notification message: f.object.errors[:base].to_sentence if f.object.errors[:base].present? %>
  <div class="panel-group">
    <div class="panel panel-default">
      <div class="panel-heading"> fill the card application form </div>
      <div class="panel-body">
  <div class="form-inputs">
    <%= f.input :card_name, lebel: "Cardholder's Name" %>
    <%= f.input :card_type, as: :select, collection: ["Credit", "Debit"]  %>
    <%= f.input :pin, as: :password %>
    <%= f.input :veriy_pin, as: :password %>
  </div>

  <div class="form-actions">
    <%= f.button :submit, class: "btn btn-primary" %>
  </div>
</div>
</div>
</div>
<% end %>

app/views/cards/edit.html.erb
<h1>Editing Card</h1>

<%= render 'form', card: @card %>

<%= link_to 'Show', @card %> |
<%= link_to 'Back', cards_path %>

app/views/cards/index.html.erb
<% if Card.where(user_id: current_user).exists? %>
<div class="content">

    <div class="container-fluid">

        <div class="row">

            <div class="col-lg-6 col-sm-6">
                <div class="card">
                    <div class="content">
                        <div class="row">

                            <div class="col-xs-5">
                                <div class="icon-big icon-warning text-center">
                                    <i class="ti-server"></i>
                                </div>
                            </div>
                            <div class="col-xs-7">
                                <div class="numbers">
                                    <p>Cards</p>
                                    <%= Card.where(user_id: current_user.id).count %>

                                </div>
                            </div>
                        </div>

                    </div>
                </div>
            </div>
            <div class="row">

                <div class="col-lg-6 col-sm-6">
                    <div class="card">
                        <div class="content">
                            <div class="row">

                                <div class="col-xs-5">
                                    <div class="icon-big icon-warning text-center">
                                        <i class="ti-credit-card"></i>
                                    </div>
                                </div>
                                <div class="col-xs-7">
                                    <div class="numbers">
                                      <% @cards.take(1).each do |a| %>

                                        <p><%= a.card_name %></p>

                                        <%= a.card_number %>
                                        <% end %>

                                    </div>
                                </div>
                            </div>

                        </div>
                    </div>
                </div>

<%else%>
<div class="content">
    <div class="container-fluid">
      <div class="row" style="margin-top:50px;">
        <div class="col-md-8 col-md-offset-2">


        <div class="card">
          <div class="image">
            <%= image_tag "page-2_img1.jpg", class: "img-fluid" %>
          </div>
          <div class="content">
            <div class="header text-center">
                <h4 class="title">Start making  your banking exprience easier</h4>
                <br />
              <%= link_to "Apply for your Credit/debits card", new_card_path, class: "btn btn-primary text-center"%>
 </div>
          </div>

        </div>
      </div>
       </div>
     </div>
   </div>
<% end %>

app/views/cards/new.html.erb
<div class="container-fluid">
  <div class="col-md-8 col-md-offset-2">
    <div class="card">
      <div class="card-title">
        <h3 class="text-center"> Apply For Your Card</h3>
      </div>
      <div class="card-body">
<%= render 'form', card: @card %>
</div>
</div>
</div>
</div>

app/views/cards/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Type:</strong>
  <%= @card.type %>
</p>

<p>
  <strong>Pin:</strong>
  <%= @card.pin %>
</p>

<p>
  <strong>Veriy pin:</strong>
  <%= @card.veriy_pin %>
</p>

<p>
  <strong>Card number:</strong>
  <%= @card.card_number %>
</p>

<p>
  <strong>Cvv:</strong>
  <%= @card.cvv %>
</p>

<p>
  <strong>Expiry:</strong>
  <%= @card.expiry %>
</p>

<p>
  <strong>Card name:</strong>
  <%= @card.card_name %>
</p>

<p>
  <strong>Account:</strong>
  <%= @card.account_id %>
</p>

<p>
  <strong>User:</strong>
  <%= @card.user_id %>
</p>

<%= link_to 'Edit', edit_card_path(@card) %> |
<%= link_to 'Back', cards_path %>