config/routes.rb
Rails.application.routes.draw do

  resources :cards
resources :contacts, only: [:new, :create]
  resources :accounts do
    resources :transfers
    resources :deposits
  end
  resources :transfers do
    resources :otps
  end
  resources :transactions, only: [:index]
  devise_for :users
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  resources :pages, only: [:show]
  authenticated :user do
    root 'accounts#index', as: "authenticated_root"
  end
    root "welcome#index"
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/account.rb
class Account < ApplicationRecord
  mount_uploader :image, ImageUploader
  extend FriendlyId
  friendly_id :account_number, use: :slugged
  belongs_to :user
  has_many :transfers, dependent: :destroy
  has_many :deposits, dependent: :destroy
  accepts_nested_attributes_for :transfers

  validates :user, presence: true
  validates :account_balance, presence: true
  before_validation :load_defaults

  def load_defaults
    if self.new_record?
      self.account_balance = 0.00
      length = 8
      self.account_number = SecureRandom.random_number(10000000000)
      self.routine_number = SecureRandom.random_number(100000000)
      self.confirmed = "false"
    end
  end

end

app/models/admin_user.rb
class AdminUser < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, 
         :recoverable, :rememberable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/card.rb
class Card < ApplicationRecord
  belongs_to :user
  before_validation :load_defaults

  def load_defaults
    if self.new_record?
      length = 8
      self.card_number = SecureRandom.random_number(10000000000000000)
      self.cvv = SecureRandom.random_number(1000)
      self.status = "false"
    end
  end
end

app/models/contact.rb
class Contact < MailForm::Base
    attribute :name,      :validate => true
    attribute :email,     :validate => /\A([\w\.%\+\-]+)@([\w\-]+\.)+([\w]{2,})\z/i
    attribute :file,      :attachment => true
    attribute :message
    attribute :nickname,  :captcha  => true

  # Declare the e-mail headers. It accepts anything the mail method
  # in ActionMailer accepts.

  def headers
      {
        :subject => "Support Request ",
        :to => "support@reylgroup.com",
        :from => %("#{name}" <#{email}>)
      }
    end
end

app/models/deposit.rb
class Deposit < ApplicationRecord
  belongs_to :account
  belongs_to :user
end

app/models/news.rb
class News < ApplicationRecord
end

app/models/otp.rb
class Otp < ApplicationRecord
  belongs_to :account
  belongs_to :transfer
  belongs_to :user
end

app/models/transfer.rb
class Transfer < ApplicationRecord
  belongs_to :user
  belongs_to :account
  has_many :otps
  accepts_nested_attributes_for :otps

  before_validation :load_defaults

  def load_defaults
    if self.new_record?
      self.otp = SecureRandom.random_number(1000000)
      self.status = "In Progress"
    end
  end
end

app/models/user.rb
class User < ApplicationRecord
  mount_uploader :avatar, AvatarUploader

  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable, :confirmable, :lockable
has_many :accounts
has_many :transfers
has_many :otps
has_many :deposits
has_many :cards
end

app/controllers/accounts_controller.rb
class AccountsController < ApplicationController
  layout "accounts"

  before_action :find_account, only: [ :show, :edit, :update, :destroy]
  before_action :authenticate_user!
  def index
    @users = User.where(user_id: current_user)
    @accounts = Account.where(user_id: current_user).order('created_at DESC')
  end

  def show
        @transfer = @account.transfers.build
  end

  def new
    @account = current_user.accounts.build
    #@account.transfers.build

  end

  def create
    @account = current_user.accounts.build(account_params)
    if @account.save
      user = User.find_by_id(@account.user_id)
      account = @account
      AccountMailer.account_email(user, account).deliver
      redirect_to @account, notice: "Account Successfully Created"
    else
      render 'new'
    end
  end
  def edit

  end

  def update
    if @account.update(account_params)
      redirect_to @account
    else
      render 'edit'
    end
  end
  #  def destroy
  #    @account.destroy
  #  respond_to do |format|
  #    format.html { redirect_to accounts_url, notice: 'Account was successfully destroyed.' }
  #    format.json { head :no_content }
  #  end
  #  end
    private
    def find_account
      @account = Account.friendly.find(params[:id])
    end
      def account_params
        params.require(:account).permit(:confirmed, :account_balance, :account_number, :phone_number, :dob, :routine_number, :user_id, :slug, :account_type, :account_pin, :image, :mother_name)
      end
end

app/controllers/news_controller.rb
class NewsController < InheritedResources::Base

  private

    def news_params
      params.require(:news).permit(:title, :body, :date)
    end
end

app/controllers/otps_controller.rb
class OtpsController < ApplicationController
  layout "account"
    #before_action :find_Account
    before_action :authenticate_user!

def new


end
    def create
      @transfer = Transfer.find(params[:transfer_id])
      @otp = @transfer.otps.create(otp_params)
      @otp.user_id = current_user.id

         redirect_to root_path, notice: "transfer successfully confirmed and in progress"

    end

    private
    def find_account
      @account = Account.find(params[:id])
    end
    def find_transfer
      @transfer = @account.transfers.find(params[:id])
    end

    def find_otp
    end

    def otp_params
      params.require(:otp).permit( :transfer_id, :user_id, :account_id, :otp)
    end

end

app/helpers/accounts_helper.rb
module AccountsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/cards_helper.rb
module CardsHelper
end

app/helpers/contacts_helper.rb
module ContactsHelper
end

app/helpers/deposits_helper.rb
module DepositsHelper
end

app/helpers/news_helper.rb
module NewsHelper
end

app/helpers/otps_helper.rb
module OtpsHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/transfers_helper.rb
module TransfersHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/accounts/_form.html.erb
  <%= simple_form_for (@account), class: "form-horizontal" do |f| %>
  <%= f.error_notification %>
  <div class="panel-group">
    <div class="panel panel-default">
      <div class="panel-heading">Personal Information </div>
      <div class="panel-body">
        <div class="row">
          <div class="col-md-12">
            <%= f.input :account_type, :as => :select, collection: ["Checkings", "Savings", "Credit"] %>
          </div>
        </div>

          <div class="row">
            <div class="col-md-12">
                <%= f.input :phone_number, required: true %>
            </div>
            </div>
            <div class="row">


            <div class="col-md-12 form-group">
              <%= f.input :dob, label: "Date Of Birth", as: :date, :start_year => 1910, :end_year => 2010, required: true, class: "form-control border-input" %>
            </div>
</div>


        <div class="row">
        <div class="col-md-12">
          <p>Please Upload a Vaild ID </p>
            <%= f.input :image, as: :file, placeholder: "Upload a Vaild ID Card" %>
        </div>
      </div>
        </div>
      </div>
    </div>

        <div class="panel-group">
          <div class="panel panel-default">
            <div class="panel-heading">Account Security </div>
            <div class="panel-body">
              <div class="row">
              <div class="col-md-12">
                <%= f.input :mother_name, label: "Your Mother's maiden Name" %>
              </div>
            </div>
              <div class="row">
                <div class="col-md-12">
                  <%= f.input :account_pin, as: :password, required: true %>
                </div>
              </div>

            </div>
          </div>
        </div>

    <div class="row">
      <div class="col-md-12">
          <%= f.button :submit, class: "btn btn-primary" %>
      </div>
    </div>
<% end %>

app/views/accounts/edit.html.erb
<div class="content">
<div class="container-fluid">
  <div class="row">
  <div class="col-md-8 ">
    <div class="card">
      <div class="content">


      <div class="card-title">
        <h3 class="text-center"> Account Information</h3>
      </div>
      <div class="card-body">
        <%= render 'form', account: @account %>
            </div>
    </div>
  </div>
  </div>
  <div class="col-md-4">
    <div class="content">
      <div class="card card-image">

        <%= image_tag (@account.image_url.to_s), class:" img-responsive"  %>
        <div class="card-title">
        <h4 class="text-center">  Identity Card </div>
        </div>
      </div>
    </div>
  </div>
</div>
</div>
</div>

app/views/accounts/index.html.erb
<% content_for(:body_attributes) do %>
data-turbolinks="false"
<% end %>
<% if Account.where(user_id: current_user.id).exists?%>
<% @accounts.take(1).each do |a| %>
<div class="content">

    <div class="container-fluid">

        <div class="row">
          <%= link_to a do %>
            <div class="col-lg-3 col-sm-6">
                <div class="card">
                    <div class="content">
                        <div class="row">

                            <div class="col-xs-5">
                                <div class="icon-big icon-warning text-center">
                                    <i class="ti-server"></i>
                                </div>
                            </div>
                            <div class="col-xs-7">
                                <div class="numbers">
                                    <p>Accounts</p>
                                    <%= Account.where(user_id: current_user.id).count %>

                                </div>
                            </div>
                        </div>
                        <div class="footer">
                            <hr />
                            <div class="stats">
                                <i class="ti-reload"></i> Updated now
                            </div>
                        </div>
                    </div>
                </div>
            </div>
            <% end %>
            <div class="col-lg-3 col-sm-6">
                <div class="card">
                    <div class="content">
                        <div class="row">
                            <div class="col-xs-5">
                                <div class="icon-big icon-success text-center">
                                    <i class="ti-wallet"></i>
                                </div>
                            </div>
                            <div class="col-xs-7">
                                <div class="numbers">

                                    <p>Revenue</p>
                                    $<%= a.account_balance %>
                                </div>
                            </div>
                        </div>
                        <div class="footer">
                            <hr />
                            <div class="stats">
                                <i class="ti-calendar"></i> Last day
                            </div>
                        </div>
                    </div>
                </div>
            </div>
            <div class="col-lg-3 col-sm-6">
                <div class="card">
                    <div class="content">
                        <div class="row">
                            <div class="col-xs-5">
                                <div class="icon-big icon-danger text-center">
                                    <i class="ti-id-badge"></i>
                                </div>
                            </div>
                            <div class="col-xs-7">
                                <div class="numbers">
                                    <p>Account Number</p>
                                    <%= a.account_number %>

                                </div>
                            </div>
                        </div>
                        <div class="footer">
                            <hr />
                            <div class="stats">
                                <i class="ti-id-badge"></i> Routine Number <%= a.routine_number %>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
            <div class="col-lg-3 col-sm-6">
                <div class="card">
                    <div class="content">
                        <div class="row">
                            <div class="col-xs-5">
                                <div class="icon-big icon-info text-center">
                                    <i class="ti-credit-card"></i>
                                </div>
                            </div>
                            <div class="col-xs-7">
                                <div class="numbers">
                                  <%= link_to a do %>
                                    <p>Funds</p>
                                        <small>Transfer </small>
                                    <%end%>
                                </div>
                            </div>
                        </div>
                        <div class="footer">
                            <hr />
                            <div class="stats">
                                <i class="ti-reload"></i> <%= a.account_type %>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <div class="row">

            <div class="col-md-12">
                <div class="card">
                    <div class="header">
                        <h4 class="title">Users Behavior</h4>
                        <p class="category">24 Hours performance</p>
                    </div>
                    <div class="content">
                        <div id="chartHours" class="ct-chart"></div>
                        <div class="footer">
                            <div class="chart-legend">
                                <i class="fa fa-circle text-info"></i>
                                <i class="fa fa-circle text-danger"></i>
                                <i class="fa fa-circle text-warning"></i>
                            </div>
                            <hr>
                            <div class="stats">
                                <i class="ti-reload"></i> Updated 3 minutes ago
                            </div>
                        </div>
                    </div>
                </div>
            </div>

        </div>

    <!--    <div class="row">
            <div class="col-md-6">
                <div class="card">

                    <div class="header">
                        <h4 class="title">Email Statistics</h4>
                        <p class="category">Last Campaign Performance</p>
                    </div>
                    <div class="content">
                        <div id="chartPreferences" class="ct-chart ct-perfect-fourth"></div>

                        <div class="footer">
                            <div class="chart-legend">
                                <i class="fa fa-circle text-info"></i> Open
                                <i class="fa fa-circle text-danger"></i> Bounce
                                <i class="fa fa-circle text-warning"></i> Unsubscribe
                            </div>
                            <hr>
                            <div class="stats">
                                <i class="ti-timer"></i> Campaign sent 2 days ago
                            </div>
                        </div>
                    </div>
                </div>
            </div>
            <div class="col-md-6">
                <div class="card ">
                    <div class="header">
                        <h4 class="title">2015 Sales</h4>
                        <p class="category">All products including Taxes</p>
                    </div>
                    <div class="content">
                        <div id="chartActivity" class="ct-chart"></div>

                        <div class="footer">
                            <div class="chart-legend">
                                <i class="fa fa-circle text-info"></i> Tesla Model S
                                <i class="fa fa-circle text-warning"></i> BMW 5 Series
                            </div>
                            <hr>
                            <div class="stats">
                                <i class="ti-check"></i> Data information certified
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div> -->
    </div>
</div>
  <%end%>
<% else %>

      <div class="container">
        <div class="col-md-8 col-md-offset-2" style="margin-top:120px;">

          <div class="card">
            <div class="row">
              <div class="col-md-8 col-md-offset-2">
                <p class="text-center">
                <%= image_tag "logo.svg", class: "text-center" %>
              </div>
              </div>


            <div class="card-title">
              <h3 class="text-center"> Enroll  Account </h3>
            </div>

            <div class="card-body">
              <div class="text-center" style="padding-top:20px; padding-bottom:20px;">
                <%= link_to "Create Account", new_account_path, class: "btn btn-info btn-fill btn-wd" %>
                <br />
                <br />
                <%= link_to "Sign-out", destroy_user_session_path, method: :delete %>

              </div>
            </div>
          </div>
        </div>
      </div>
  <% end %>
  <%= javascript_include_tag 'chartist.min' %>
  <%= javascript_include_tag 'demo' %>


  <script type="text/javascript">
      $(document).ready(function(){

          demo.initChartist();

          $.notify({
              icon: 'ti-gift',
              message: "Welcome to <b>Reyl & Cie Bank </b> -"

            },{
                type: 'success',
                timer: 4000
            });

      });
  </script>

app/views/accounts/new.html.erb
<div class="container">
  <div class="col-md-8 col-md-offset-2">
    <div class="card">
      <div class="card-title">
        <h3 class="text-center"> Account Registration Form</h3>
      </div>
      <div class="card-body">
        <%= render 'form', account: @account %>
            </div>
    </div>
  </div>
</div>

app/views/accounts/show.html.erb
<div class="content">
    <div class="container-fluid">
      <div class="row">
        <div class="col-lg-4 col-sm-6">
            <div class="card">
                <div class="content">
                    <div class="row">
                      <div class="col-xs-5">
                          <div class="icon-big icon-success text-center">
                              <i class="ti-wallet"></i>
                          </div>
                      </div>
                      <div class="col-xs-7">
                          <div class="numbers">

                              <p>Revenue</p>
                              $<%= @account.account_balance %>
                          </div>
                      </div>
                  </div>

              </div>
          </div>
        </div>
        <div class="col-lg-4 col-sm-6">
            <div class="card">
                <div class="content">
                    <div class="row">
                      <div class="col-xs-5">
                          <div class="icon-big icon-success text-center">
                              <i class="ti-user"></i>
                          </div>
                      </div>
                      <div class="col-xs-7">
                          <div class="numbers">
                          <p>  Account Information </p>
                            <%= link_to edit_account_path, class: "btn btn-primary" do %>
                            view
                              <% end %>
                          </div>
                      </div>
                  </div>

              </div>
          </div>
        </div>
        <div class="col-lg-4 col-sm-6">
            <div class="card">
                <div class="content">
                    <div class="row">
                      <div class="col-xs-5">
                          <div class="icon-big icon-success text-center">
                              <i class="ti-credit-card"></i>
                          </div>
                      </div>
                      <div class="col-xs-7">
                          <div class="numbers">

                              <p>Transfer</p>
                              <%= button_tag :new_transfer, id: "tr_btn", class: "btn btn-primary" do %>
                                Make a transfer
                                <%end%>
                          </div>
                      </div>
                  </div>

              </div>
          </div>
        </div>


    </div>
    <div class="row">
      <div class="content">
        <div class="row">
            <div class="col-md-12">
                <div class="card">
                    <div class="header">
                        <h4 class="title">Account History</h4>
                        <p class="category"></p>
                    </div>
                    <div class="content table-responsive table-full-width">
                        <table class="table table-striped">
                            <thead>
                              <th>Transfer Type</th>
                              <th>Account Name </th>
                              <th>Amount</th>
                              <th> Status </th>
                            </thead>
                            <tbody>
                              <%= render :partial => @account.deposits %>

                              <%= render :partial => @account.transfers %>

    </tbody>
  </table>
</div>
</div>
</div>
</div>


      </div>
    </div>

    </div>
  </div>
  <!---second modal for withdraw -->
  <div class="modal" id="transModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
    <div class="modal-dialog bounceIn animated" role="document">
      <div class="modal-content">
        <div class="modal-header">
          <h5 class="modal-title" id="exampleModalLabel">Make A transfer</h5>
          <button type="button" class="close" data-dismiss="modal" aria-label="Close">
            <span aria-hidden="true">&times;</span>
          </button>
        </div>
        <div class="modal-body">

            <div class="row" >
                    <div class="card">
                        <div class="content">
                            <div class="row">
                                <div class="col-xs-5">
                                    <div class="icon-big icon-success text-center">
                                        <i class="ti-wallet"></i>
                                    </div>
                                </div>
                                <div class="col-xs-7">
                                    <div class="numbers">

                                        <p>Revenue</p>
                                        $<%= @account.account_balance %>
                                    </div>
                                </div>
                            </div>

                        </div>
                    </div>
                </div>

            <%= render "transfers/form" %>

        </div>
          <div class="modal-footer">
            <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>

          </div>
        </div>
      </div>
    </div>


  <%= javascript_include_tag 'view' %>
  <script type="text/javascript">
  $(document).ready(function() {
    view.init();
  });
  </script>